### ISSUE TITLE
Add the possibility to keep the todos when the application closes.

### ISSUE THREAD

**Issue by LacoutierePaul** [LacoutierePaul/Todo_list-Paul_Lacoutiere-CDOF1#3]
I would like to add a new feature in this project.   
The actual problem is that when we close the application, all the todos that we created or updated are deleted.
I would like you to add the possibility to save the todos we have created.
So when we launched again the application, the todos are loaded and we can still saw them.

**Comment by mathiasbalian** [comment]
Hello, I would like to contribute to this issue. 
Would you be okay if the program was storing the todos in a text file contained in the project directory ?
